# Copyright (c) 2022-2025, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
# See LICENSE for license information.

name: Build PyTorch Wheel
description: Builds a PyTorch wheel for TransformerEngine

inputs:
  release-version:
    description: 'The release version to use for the build'
    required: true
  python-version:
    description: 'The Python version to use for the build'
    required: true
  cuda-version:
    description: 'The CUDA version to use for the build'
    required: true
  cudnn-version:
    description: 'The cuDNN version to use for the build'
    required: true
  torch-version:
    description: 'The PyTorch version to use for the build'
    required: true
  cxx11_abi:
    description: 'Enable torch flag C++11 ABI (TRUE/FALSE)'
    required: true
  base-image:
    description: 'The base image to use for the build'
    required: false
  aarch:
    description: 'The architecture to use for the build'
    required: true
outputs:
  get_cu_wheel_name:
    description: 'The name of the built wheel'
    value: ${{ steps.get_cu_wheel_name.outputs.name }}
  get_torch_wheel_name:
    description: 'The name of the built wheel'
    value: ${{ steps.get_torch_wheel_name.outputs.name }}

runs:
  using: 'composite'
  steps:
    - name: Move /var/lib/docker/
      shell: bash -euxo pipefail {0}
      run: sudo mv /var/lib/docker/ "${GITHUB_WORKSPACE}/docker"

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 5120
        temp-reserve-mb: 32
        swap-size-mb: 10240
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restore /var/lib/docker/
      shell: bash -euxo pipefail {0}
      run: sudo sh -c "mv ${GITHUB_WORKSPACE}/docker/* /var/lib/docker"

    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.release-version }}
        submodules: recursive

    - name: Checkout build tools
      uses: actions/checkout@v4
      with:
        path: build-tools
        submodules: recursive

    - name: Build manylinux base image
      shell: bash -euxo pipefail {0}
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: |
        cd build_tools/wheel_utils
        docker build \
          -t manylinux-base-image \
          -f Dockerfile.${{ inputs.aarch }} \
          --build-arg PYTHON_VERSION=$(echo $PYTHON_VERSION | sed 's/\.//') \
          --build-arg BUILD_JAX=false \
          --build-arg BUILD_PYTORCH_BDIST=true \
          .

    - name: Build image
      shell: bash -euxo pipefail {0}
      env:
        BASE_IMAGE: ${{ inputs.base-image }}
        PYTHON_VERSION: ${{ inputs.python-version }}
        TORCH_VERSION: ${{ inputs.torch-version }}
      run: |
        if [[ "${BASE_IMAGE}" == "" ]]; then
          docker build \
            -t transformer-engine-build \
            -f build-tools/.github/actions/build-pytorch-wheel/Dockerfile \
            --build-arg PYTHON_VERSION=$(echo $PYTHON_VERSION | sed 's/\.//') \
            --build-arg TORCH_VERSION=$TORCH_VERSION \
            --build-arg MANYLINUX_BASE_IMAGE=manylinux-base-image  \
            .
        else
          docker pull ${BASE_IMAGE}
          docker tag ${BASE_IMAGE} transformer-engine-build
        fi
    - name: Build wheels
      shell: bash -euxo pipefail {0}
      id: build_wheel
      env:
        CXX11_ABI: ${{ inputs.cxx11_abi }}
      run: |
        echo ::group::Build wheel

        docker run \
          -v $(pwd):/TransformerEngine \
          -v $(pwd)/wheelhouse:/wheelhouse \
          -e MAX_JOBS=2 \
          transformer-engine-build

        echo ::endgroup::

    - name: Log Built Wheels
      shell: bash -euxo pipefail {0}
      run: |
        ls wheelhouse

    - name: Get CU wheel name
      shell: bash -euxo pipefail {0}
      id: get_cu_wheel_name
      run: |
        name=$(ls wheelhouse/transformer_engine_cu*.whl)

        mv $name $(basename $name)
        echo "name=$(basename $name)" | tee -a "$GITHUB_OUTPUT"

    - name: Get torch wheel name
      shell: bash -euxo pipefail {0}
      id: get_torch_wheel_name
      run: |
        name=$(ls wheelhouse/transformer_engine_torch*.whl)
        target_name=$(docker run -v $(pwd):/TransformerEngine -v $(pwd)/wheelhouse:/wheelhouse -w /TransformerEngine/transformer_engine/pytorch transformer-engine-build bash -c '/opt/python/cp${PYTHON_VERSION}-cp${PYTHON_VERSION}/bin/pip install wheel; /opt/python/cp${PYTHON_VERSION}-cp${PYTHON_VERSION}/bin/python -c "import setup; print(setup.get_wheel_url()[1])"' | tail -1)

        mv $name $target_name
        echo "name=$$target_name" | tee -a "$GITHUB_OUTPUT"
